dist: trusty
language: python

matrix:
  include:
#    - os: linux
#      sudo: required
#      python: 2.7
#    - os: linux
#      sudo: required
#      python: 3.5
#    - os: linux
#      sudo: required
#      python: 3.6
    - os: osx
      language: generic
      env: PYTHON=2.7.15
# python:
#   - "2.7"
#   - "3.4"
#   - "3.5"
#   - "3.6"
#   - "3.6-dev"
#   - "3.7-dev"
#   - "nightly"

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi

# command to install dependencies
install:
  - python -m pip install -U pip==18.0
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

# command to run before tests start
before_script:
  - PYTHONPATH=. python tests/rest_tests/prepare.py

# command to run tests
script: PYTHONPATH=. nosetests -s -v -x --with-xunit --processes=8 --process-restartworker --process-timeout=900 tests/

